# Generated by Django 4.1.5 on 2023-03-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_active_band_user_active_tour_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_band',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active_tour',
        ),
    ]
