# Generated by Django 4.1.5 on 2023-03-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        ('bands', '0002_remove_banduser_is_owner_band_owner_alter_band_users'),
        ('authentication', '0004_user_active_band_user_active_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bands.band'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
