# Generated by Django 4.1.5 on 2023-03-13 13:40

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_remove_banduser_is_owner_band_owner_alter_band_users'),
        ('tours', '0001_initial'),
        ('authentication', '0005_alter_user_active_band_alter_user_active_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.band'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
