# Generated by Django 4.1.5 on 2023-03-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_band'),
        ('bands', '0002_remove_banduser_is_owner_band_owner_alter_band_users'),
        ('authentication', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_band',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.band'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_tour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour'),
        ),
    ]
