# Generated by Django 4.1.7 on 2023-04-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description',
            new_name='name',
        ),
    ]
