# Generated by Django 4.2 on 2023-05-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
