# Generated by Django 4.1.7 on 2023-04-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0005_alter_timeslot_end_location_and_more'),
        ('dates', '0005_alter_date_date'),
        ('venues', '0005_venue_location'),
        ('gapi', '0002_rename_description_location_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Place',
        ),
    ]
