# Generated by Django 4.2 on 2023-05-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_initial"),
        ("gapi", "0002_alter_place_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="places", to="contacts.contact"
            ),
        ),
    ]
