# Generated by Django 4.2 on 2023-05-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_placecontact"),
        ("gapi", "0003_place_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="places", to="contacts.placecontact"
            ),
        ),
    ]
