# Generated by Django 4.1.7 on 2023-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapi', '0003_rename_location_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
