# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0007_date_prospects_delete_prospect_delete_statustype"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dates.date"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Phone", "Phone"),
                            ("Email", "Email"),
                            ("Facebook", "Facebook"),
                            ("Instagram", "Instagram"),
                            ("WhatsApp", "WhatsApp"),
                            ("Twitter", "Twitter"),
                            ("Other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("value", models.URLField(max_length=500)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
