# Generated by Django 4.1.7 on 2023-03-31 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_remove_contact_email_remove_contact_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="creator_id",
            new_name="creator",
        ),
    ]
