# Generated by Django 4.1.7 on 2023-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_rename_creator_id_contact_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmethod",
            name="value",
            field=models.TextField(max_length=500),
        ),
    ]
