# Generated by Django 4.1.7 on 2023-03-31 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeslot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("start_location", models.TextField(blank=True, default="")),
                ("end_location", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Event", "Event"),
                            ("Drive", "Drive"),
                            ("Flight", "Flight"),
                            ("Meeting", "Meeting"),
                        ],
                        max_length=25,
                    ),
                ),
                ("after_midnight", models.BooleanField(default=False)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="schedule",
                        to="dates.date",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
