# Generated by Django 4.1.5 on 2023-03-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeslotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('start_location', models.TextField(blank=True)),
                ('end_location', models.TextField(blank=True)),
                ('after_midnight', models.BooleanField(default=False)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dates.date')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timeslots.timeslottype')),
            ],
        ),
    ]
