# Generated by Django 4.1.5 on 2023-03-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_alter_date_location_alter_date_notes_and_more'),
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='dates.date'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_location',
            field=models.TextField(blank=True, default=''),
        ),
    ]
