# Generated by Django 4.1.7 on 2023-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeslots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
