# Generated by Django 4.1.7 on 2023-03-31 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0007_date_prospects_delete_prospect_delete_statustype"),
        ("timeslots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="schedule",
                to="dates.date",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timeslots.timeslottype",
            ),
        ),
        migrations.AlterField(
            model_name="timeslottype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
