# Generated by Django 4.1.7 on 2023-04-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0003_date_political_location"),
        ("timeslots", "0002_alter_timeslot_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="dates.date",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Event", "Event"),
                    ("Drive", "Drive"),
                    ("Flight", "Flight"),
                    ("Meeting", "Meeting"),
                ],
                default=("Event", "Event"),
                max_length=25,
            ),
        ),
    ]
