# Generated by Django 4.1.5 on 2023-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0002_alter_timeslot_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
