# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeslots", "0003_alter_timeslottype_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Event", "Event"),
                    ("Drive", "Drive"),
                    ("Flight", "Flight"),
                    ("Meeting", "Meeting"),
                ],
                default="",
                max_length=25,
            ),
            preserve_default=False,
        ),
    ]
