# Generated by Django 4.1.5 on 2023-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0003_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslottype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
