# Generated by Django 4.1.7 on 2023-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeslots", "0003_alter_timeslot_date_alter_timeslot_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeslot",
            old_name="after_midnight",
            new_name="end_after_midnight",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="start_after_midnight",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Event", "Event"),
                    ("Travel", "Travel"),
                    ("Flight", "Flight"),
                    ("Meeting", "Meeting"),
                ],
                default="Event",
                max_length=25,
            ),
        ),
    ]
