# Generated by Django 4.1.7 on 2023-04-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gapi', '0001_initial'),
        ('timeslots', '0004_rename_after_midnight_timeslot_end_after_midnight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_location', to='gapi.location'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_location', to='gapi.location'),
        ),
    ]
