# Generated by Django 4.1.7 on 2023-03-31 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeslots", "0004_alter_timeslot_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeslotType",
        ),
    ]
