# Generated by Django 4.1.5 on 2023-03-17 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'Name must be unique.'}, max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.band')),
                ('users', models.ManyToManyField(blank=True, to='bands.banduser')),
            ],
        ),
    ]
