# Generated by Django 4.1.5 on 2023-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
