# Generated by Django 4.1.5 on 2023-03-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_remove_banduser_is_owner_band_owner_alter_band_users'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
    ]
