# Generated by Django 4.1.5 on 2023-03-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_remove_banduser_is_owner_band_owner_alter_band_users'),
        ('tours', '0002_alter_tour_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='users',
            field=models.ManyToManyField(blank=True, to='bands.banduser'),
        ),
    ]
