# Generated by Django 4.0.4 on 2022-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_name_alter_tour_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
