# Generated by Django 4.0.4 on 2022-09-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventType',
            new_name='TimeslotType',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_location',
            field=models.TextField(null=True),
        ),
    ]
