# Generated by Django 4.0.4 on 2022-09-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_eventtype_timeslottype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='event_type',
            new_name='type',
        ),
    ]
