# Generated by Django 4.1.7 on 2023-03-31 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="creator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venues",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="formatted_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="venue",
            name="lng",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="venue",
            name="place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
