# Generated by Django 4.1.7 on 2023-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_alter_venue_formatted_address_alter_venue_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="lat",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venue",
            name="lng",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
