# Generated by Django 4.1.7 on 2023-03-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_venue_creator_alter_venue_formatted_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
