# Generated by Django 4.1.7 on 2023-04-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gapi', '0001_initial'),
        ('venues', '0004_alter_venue_lat_alter_venue_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gapi.location'),
            preserve_default=False,
        ),
    ]
