# Generated by Django 4.1.7 on 2023-03-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNCONFIRMED", "UNCONFIRMED"),
                    ("INQUIRY SENT", "INQUIRY SENT"),
                    ("UNAVAILABLE", "UNAVAILABLE"),
                    ("OFFER RECEIVED", "OFFER RECEIVED"),
                    ("CONFIRMED", "CONFIRMED"),
                ],
                default="UNCONFIRMED",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="StatusType",
        ),
    ]
