# Generated by Django 4.1.7 on 2023-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="date",
            field=models.DateField(default="2023-04-04"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospect",
            name="hold",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNCONFIRMED", "UNCONFIRMED"),
                    ("INQUIRY SENT", "INQUIRY SENT"),
                    ("HOLD", "HOLD"),
                    ("UNAVAILABLE", "UNAVAILABLE"),
                    ("OFFER RECEIVED", "OFFER RECEIVED"),
                    ("CONFIRMED", "CONFIRMED"),
                ],
                default="UNCONFIRMED",
                max_length=50,
            ),
        ),
    ]
