# Generated by Django 4.1.7 on 2023-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
