# Generated by Django 4.1.7 on 2023-04-05 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0002_logentry_date_prospect_hold_alter_prospect_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="date",
        ),
    ]
