# Generated by Django 4.1.7 on 2023-04-30 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("gapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("notes", models.TextField(blank=True)),
                ("deal", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("is_show_day", models.BooleanField(default=False)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True, related_name="dates", to="contacts.datecontact"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gapi.place",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
