# Generated by Django 4.1.5 on 2023-03-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
