# Generated by Django 4.1.5 on 2023-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_alter_date_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='date',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='date',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
