# Generated by Django 4.1.7 on 2023-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0003_alter_date_location_alter_date_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="date",
            name="place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="date",
            name="deal",
            field=models.TextField(blank=True, default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="date",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="date",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="date",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
