# Generated by Django 4.1.7 on 2023-04-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gapi', '0001_initial'),
        ('dates', '0003_date_political_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='date',
            name='political_location',
        ),
        migrations.AlterField(
            model_name='date',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gapi.location'),
        ),
    ]
