# Generated by Django 4.1.7 on 2023-04-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_remove_date_place_id_remove_date_political_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
