# Generated by Django 4.1.7 on 2023-03-31 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0005_statustype_prospect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prospect",
            name="date",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="status",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="venue",
        ),
    ]
