# Generated by Django 4.1.7 on 2023-04-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_alter_date_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='location',
            new_name='place',
        ),
    ]
