# Generated by Django 4.1.7 on 2023-03-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0006_remove_prospect_date_remove_prospect_status_and_more"),
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="prospects",
            field=models.ManyToManyField(
                blank=True, related_name="prospect_dates", to="prospects.prospect"
            ),
        ),
        migrations.DeleteModel(
            name="Prospect",
        ),
        migrations.DeleteModel(
            name="StatusType",
        ),
    ]
