# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_datecontact_contactmethod"),
        ("dates", "0007_date_prospects_delete_prospect_delete_statustype"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="dates", to="contacts.datecontact"
            ),
        ),
    ]
