# Generated by Django 4.1.5 on 2023-03-09 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banduser',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='band',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='users',
            field=models.ManyToManyField(related_name='band_users', through='bands.BandUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
