# Generated by Django 4.0.4 on 2022-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_date_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
