# Generated by Django 4.0.4 on 2022-09-09 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0007_rename_event_type_timeslot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(error_messages={'unique': 'Name must be unique.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
