# Generated by Django 4.1.5 on 2023-03-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tour_name_alter_tour_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
