# Generated by Django 4.1.5 on 2023-03-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_date_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
